### ISSUE TITLE
Meta data of JEM-X light curves contain spaces instead of '+' or '-'

### ISSUE THREAD

**Issue by ferrigno** [oda-hub/dispatcher-plugin-integral#1]
The code that gets the source names from ddosa seem the one around this line, but it does not perform the string replacement that we search.

https://github.com/oda-hub/dispatcher-plugin-integral/blob/fe2ccb7279b90d0c378a5e359919931cc873a5bf/cdci_osa_plugin/osa_lightcurve_query.py#L161

**Comment by ferrigno** [comment]
It is peculiar of JEM-X, not of ISGRI

**Comment by volodymyrss** [comment]
additional comment from @ferrigno (https://github.com/oda-hub/oda_api/issues/43):


from oda_api.api import DispatcherAPI disp=DispatcherAPI(url='http://dispatcher.staging.internal.odahub.io/', instrument='mock')

data_collection.show()
ID=0 prod_name=jemx_spectrum_0_GX5-1_jemx_spectrum meta_data: {'src_name': 'GX 5-1', 'product': 'jemx_spectrum'}
...
ID=3 prod_name=jemx_spectrum_3_H1820-303_jemx_spectrum meta_data: {'src_name': 'H 1820-303', 'product': 'jemx_spectrum'}
...

provides names with a "-" minus, but the accessed name is with "m"

data_collection.jemx_spectrum_0_GX5m1_jemx_spectrum

can we correct this behavior ?

[I remember to have it raised already, but I do not find this issue anymore]

**Comment by burnout87** [comment]
This has been solved with #41
