### ISSUE TITLE
can we test with token passed with oda_api?

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-plugin-integral#10]
I do not think this was done yet?

test would verify that condition set by the plugin is properly applied for the selected role.

**Comment by burnout87** [comment]
Very good point!
No, we didn't, or at least, I never did.

This will be the first test the I write using the oda_api.

**Comment by volodymyrss** [comment]
it is easier to write with oda_api since it does much of the interaction, but then it may become unclear we are still testing plugin or oda_api.

So it's good to add some with api but not all.

I marked the api tests like so:
https://github.com/oda-hub/dispatcher-plugin-integral/blob/master/tests/test_isgri_plugin.py#L189

**Comment by burnout87** [comment]
> it is easier to write with oda_api since it does much of the interaction, but then it may become unclear we are still testing plugin or oda_api.
> 
> So it's good to add some with api but not all.
> 
> I marked the api tests like so:
> https://github.com/oda-hub/dispatcher-plugin-integral/blob/master/tests/test_isgri_plugin.py#L189

Wait, even if this is a test not related to any plugin in particular?

**Comment by volodymyrss** [comment]
it is related to how the condition set by the plugin is properly applied for the selected role.

i.e. to test that restricted role can not run some requests.

**Comment by burnout87** [comment]
#12
