### ISSUE TITLE
	failed: isgri_lc 	TypeError('Cannot compare structured or void to non-void arrays.')

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-plugin-integral#106]
it's a bug and it obstucts @ferrigno . Not sure if this is not plugin. I try to address quickly but I am a bit blocked by the meeting.

if @burnout87 can help quickly it's much appreciated. Else I do a bit later.

https://sentry.io/organizations/cdci/issues/3805109826/?query=is%3Aunresolved&referrer=issue-stream

![image](https://user-images.githubusercontent.com/3909535/207638005-9f4ec84e-925a-4c19-bcae-cfaf3dcf1b09.png)

**Comment by volodymyrss** [comment]
@ferrigno I was able to see a lightcurve in you "finished empty" request. Since it's only post-processing, just clicking on links should be enough (i.e. no caches are affected).

**Comment by ferrigno** [comment]
Reissuing the query worked.  The New source in Cyg X-1 looks reasonable.
