### ISSUE TITLE
inconsistency in ISGRI and JEM-X product show

### ISSUE THREAD

**Issue by ferrigno** [oda-hub/dispatcher-plugin-integral#40]
from oda_api.api import DispatcherAPI
disp=DispatcherAPI(url='http://dispatcher.staging.internal.odahub.io', instrument='mock')
par_dict={\
"src_name": "4U 1700-377",\
"RA": "270.80",\
"DEC": "-29.80",\
"T1": "2021-05-01",\
"T2": "2021-05-05",\
"T_format": "isot",\
"instrument": "jemx",\
"osa_version": "OSA11.0",\
"radius": "4",\
"max_pointings": "50",\
"integral_data_rights": "all-private",\
"jemx_num": "1",\
"E1_keV": "3",\
"E2_keV": "20",\
"product_type": "Real",\
"detection_threshold": "5",\
"product": "jemx_lc",\
"time_bin": "4",\
"time_bin_format": "sec",\
"catalog_selected_objects": "1,2,3",
"selected_catalog" :'{"cat_frame": "fk5", "cat_coord_units": "deg", "cat_column_list": [[0, 1, 2], ["GX 5-1", "MAXI SRC", "H 1820-303"], [96.1907958984375, 74.80066680908203, 66.31670379638672], [270.2771301269531, 270.7560729980469, 275.914794921875], [-25.088342666625977, -29.84027099609375, -30.366628646850586], [0, 1, 0], [0.05000000074505806, 0.05000000074505806, 0.05000000074505806]], "cat_column_names": ["meta_ID", "src_names", "significance", "ra", "dec", "FLAG", "ERR_RAD"], "cat_column_descr": [["meta_ID", "<i8"], ["src_names", "<U10"], ["significance", "<f8"], ["ra", "<f8"], ["dec", "<f8"], ["FLAG", "<i8"], ["ERR_RAD", "<f8"]], "cat_lat_name": "dec", "cat_lon_name": "ra"}',
"token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6IkNhcmxvLkZlcnJpZ25vQHVuaWdlLmNoIiwibmFtZSI6ImNmZXJyaWdubyIsInJvbGVzIjoiYXV0aGVudGljYXRlZCB1c2VyLCBhZG1pbmlzdHJhdG9yLCBjb250ZW50IG1hbmFnZXIsIGdlbmVyYWwsIGludGVncmFsLXByaXZhdGUtcWxhLCBtYWdpYywgdW5pZ2UtaHBjLWZ1bGwsIHB1YmxpYy1wb29sLWhwYywgYW50YXJlcywgc2RzcyIsImV4cCI6MTYyMzEzNDg5M30.UVaNwQBGdcUly3bsQDH17X0Wa9fPz8nTWyphHP6yoBY"
}

data_collection_lc.show()

ID=0 prod_name=jemx_lc_0_H1820303  meta_data: {'src_name': 'H 1820 303', 'time_bin': 4.62963e-05, 'time': 'TIME', 'rate': 'RATE', 'rate_err': 'ERROR'}

ID=1 prod_name=jemx_lc_1_MAXISRC  meta_data: {'src_name': 'MAXI SRC', 'time_bin': 4.62963e-05, 'time': 'TIME', 'rate': 'RATE', 'rate_err': 'ERROR'}

The "-" in the source name of "H 1820-303" disappears in the "show()" method.

**Comment by burnout87** [comment]
I just re-run the previous test for JEM-X lc, and this is the output of `show()`:

```
ID=0 prod_name=jemx_lc_0_H1820m303  meta_data: {'src_name': 'H 1820-303', 'time_bin': 4.62963e-05, 'time': 'TIME', 'rate': 'RATE', 'rate_err': 'ERROR'}

ID=1 prod_name=jemx_lc_1_MAXISRC  meta_data: {'src_name': 'MAXI SRC', 'time_bin': 4.62963e-05, 'time': 'TIME', 'rate': 'RATE', 'rate_err': 'ERROR'}
```

For completeness, I also gave a try to `as_list()`:

```
[{'ID': 0, 'prod_name': 'jemx_lc_0_H1820m303', 'meta_data:': {'src_name': 'H 1820-303', 'time_bin': 4.62963e-05, 'time': 'TIME', 'rate': 'RATE', 'rate_err': 'ERROR'}}, {'ID': 1, 'prod_name': 'jemx_lc_1_MAXISRC', 'meta_data:': {'src_name': 'MAXI SRC', 'time_bin': 4.62963e-05, 'time': 'TIME', 'rate': 'RATE', 'rate_err': 'E
```

**Comment by volodymyrss** [comment]
so that's what you wanted, yes? Seems ok.

**Comment by volodymyrss** [comment]
> I just re-run the previous test for JEM-X lc, and this is the output of `show()`:
> 
> ```
> ID=0 prod_name=jemx_lc_0_H1820m303  meta_data: {'src_name': 'H 1820-303', 'time_bin': 4.62963e-05, 'time': 'TIME', 'rate': 'RATE', 'rate_err': 'ERROR'}
> 
> ID=1 prod_name=jemx_lc_1_MAXISRC  meta_data: {'src_name': 'MAXI SRC', 'time_bin': 4.62963e-05, 'time': 'TIME', 'rate': 'RATE', 'rate_err': 'ERROR'}
> ```
> 
> For completeness, I also gave a try to `as_list()`:
> 
> ```
> [{'ID': 0, 'prod_name': 'jemx_lc_0_H1820m303', 'meta_data:': {'src_name': 'H 1820-303', 'time_bin': 4.62963e-05, 'time': 'TIME', 'rate': 'RATE', 'rate_err': 'ERROR'}}, {'ID': 1, 'prod_name': 'jemx_lc_1_MAXISRC', 'meta_data:': {'src_name': 'MAXI SRC', 'time_bin': 4.62963e-05, 'time': 'TIME', 'rate': 'RATE', 'rate_err': 'E
> ```

oh, could we add a code snipplet that verifies this in there https://github.com/oda-hub/oda_test_kit

it's used for integration tests.

**Comment by burnout87** [comment]
> oh, could we add a code snipplet that verifies this in there https://github.com/oda-hub/oda_test_kit
> 

Ok, can I use this test (the one here discussed)? What is the main purpose of those tests?

**Comment by burnout87** [comment]
> > oh, could we add a code snipplet that verifies this in there https://github.com/oda-hub/oda_test_kit
> 
> Ok, can I use this test (the one here discussed)? What is the main purpose of those tests?

PS I also need to be added to the repo

**Comment by volodymyrss** [comment]
> > oh, could we add a code snipplet that verifies this in there https://github.com/oda-hub/oda_test_kit
> 
> Ok, can I use this test (the one here discussed)? What is the main purpose of those tests?

here:
> it's used for integration tests.

i.e. it's used for integration tests. I.e. the tests on the entire platform, end-to-end. They are also run in production regularly.

Please make  a PR.

**Comment by burnout87** [comment]
I still need access rights

**Comment by volodymyrss** [comment]
> I still need access rights

oh, sorry, but I do not understand - it is a public repository, yes? Is it possible to see it? To fork it? It should be!

**Comment by burnout87** [comment]
PR open

**Comment by volodymyrss** [comment]
thanks!

**Comment by volodymyrss** [comment]
I think this is done, yes? Let's see that @ferrigno  verifies.

**Comment by volodymyrss** [comment]
strange, I ran it on a different data set (https://github.com/oda-hub/oda_test_kit/blob/master/test_lc.py#L53) and git this:

```python
ID=0 prod_name=jemx_lc_0_H1820-303  meta_data: {'src_name': 'H 1820-303', 'time_bin': 4.62963e-05, 'time': 'TIME', 'rate': 'RATE', 'rate_err': 'ERROR'}

ID=1 prod_name=jemx_lc_1_MAXISRC  meta_data: {'src_name': 'MAXI SRC', 'time_bin': 4.62963e-05, 'time': 'TIME', 'rate': 'RATE', 'rate_err': 'ERROR'}

len(l_output): 
 2
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/savchenk/oda_test_kit/test_lc.py", line 53, in test_jemx_lc_source_name_formatting
    assert l_output[0]['prod_name'] == 'jemx_lc_0_H1820m303'
AssertionError
```

**Comment by volodymyrss** [comment]
could you confirm @burnout87 ? we could try few different variants

**Comment by burnout87** [comment]
I just re-run it, and for me it still works. I run the very same test

**Comment by volodymyrss** [comment]
> I just re-run it, and for me it still works. I run the very same test

the very same test you ran before or the same I updated?

**Comment by burnout87** [comment]
Actually yours.

**Comment by burnout87** [comment]
Are you running the last version of the `oda_api` ?

**Comment by volodymyrss** [comment]
yeah, I realized that was the problem. I made the requirement explicit: https://github.com/oda-hub/oda_test_kit/blob/master/test_lc.py#L20

**Comment by burnout87** [comment]
I think we can close this now ?

**Comment by volodymyrss** [comment]
maybe let's let @ferrigno review.

By the way, I made this:

https://github.com/oda-hub/doc-handbook#dealing-with-issues-emerging-in-review-and-operations

I should have made it through PR so we can all review and comment, sorry. Please feel free to suggest changes. Also let's discuss today 15h.

**Comment by ferrigno** [comment]
It does not work currently

ID=1 prod_name=isgri_lc_1_H0614+091  meta_data: {'src_name': 'H 0614+091', 'time_bin': 0.000578675871775676, 'time': 'TIME', 'rate': 'RATE', 'rate_err': 'ERROR'}

should be

ID=1 prod_name=isgri_lc_1_H0614p091  meta_data: {'src_name': 'H 0614+091', 'time_bin': 0.000578675871775676, 'time': 'TIME', 'rate': 'RATE', 'rate_err': 'ERROR'}

**Comment by ferrigno** [comment]
ID=0 prod_name=jemx_lc_0_1A1742-294  meta_data: {'src_name': '1A 1742-294', 'time_bin': 4.62963e-05, 'time': 'TIME', 'rate': 'RATE', 'rate_err': 'ERROR'}
should be
ID=0 prod_name=jemx_lc_0_1A1742m294  meta_data: {'src_name': '1A 1742-294', 'time_bin': 4.62963e-05, 'time': 'TIME', 'rate': 'RATE', 'rate_err': 'ERROR'}

**Comment by volodymyrss** [comment]
but did you update oda_api?

**Comment by ferrigno** [comment]
> but did you update oda_api?

No, now it is correct with v 1.1.15
