### ISSUE TITLE
test how default parameters are set in job id 

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-plugin-integral#56]
check that those parameters which are always set in frontend, are always set in URLs, even if not provided in api request.

**Comment by burnout87** [comment]
Quickly verified now and some tests are no longer succeding. Will provide a fixing PR.

**Comment by burnout87** [comment]
Ok, something is missing: besides setting the default values for the parameters for the specific requested query, also those for the `instrument_query` and `src_query` should be set.

Because of that a jemx test is not passing.

Dedicated PR coming soon.

**Comment by volodymyrss** [comment]
we need to be sure that the defaults match those in frontend. Do they?

**Comment by ferrigno** [comment]
It might be related to this work in progress, but I submitted three requests for jobs that should have been already done 
I received a submission email, but never a done email.
The first request was delivered in a few seconds, the others took several minutes (actually the last one is still in progress)
[ODA][submitted] isgri_spectrum first requested at 2021-09-24 14:22:04 job_id: eef3e3be
[ODA][submitted] isgri_spectrum first requested at 2021-09-24 14:24:34 job_id: c1beaf6c
[ODA][submitted] isgri_spectrum first requested at 2021-09-24 14:42:05 job_id: 38bccebb

**Comment by burnout87** [comment]
> we need to be sure that the defaults match those in frontend. Do they?

Not at that moment. I will adapt!

**Comment by volodymyrss** [comment]
> It might be related to this work in progress, but I submitted three requests for jobs that should have been already done
> I received a submission email, but never a done email.
> The first request was delivered in a few seconds, the others took several minutes (actually the last one is still in progress)
> [ODA][submitted] isgri_spectrum first requested at 2021-09-24 14:22:04 job_id: eef3e3be
> [ODA][submitted] isgri_spectrum first requested at 2021-09-24 14:24:34 job_id: c1beaf6c
> [ODA][submitted] isgri_spectrum first requested at 2021-09-24 14:42:05 job_id: 38bccebb

this work in progress is not merged and hence is not related https://github.com/oda-hub/doc-review-guidelines/issues/66

**Comment by burnout87** [comment]
Not really related to this plugin, but should the same test be performed also for other plugins (eg antares)?

**Comment by volodymyrss** [comment]
I already made an issue for another one https://github.com/oda-hub/dispatcher-plugin-integral-all-sky/issues/12
Not all will be affected. 
This mostly matters for the one with URL. But it might change something due to new defaults
