### ISSUE TITLE
isgri lightcurves do not contain XAX_E, and are occasionally empty

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-plugin-integral#6]
@burnout87  could we make a test to request ISGRI LC for a single pointing, 066500220010.001 ?

**Comment by volodymyrss** [comment]
I will make the test #7

**Comment by volodymyrss** [comment]
could you @ferrigno please check if it is ok now, even if not ideal?

**Comment by ferrigno** [comment]
There are now both TIMEDEL and XAX_E, but the light curve is displayed correctly with lcurve so I would leave it as it is.
