### ISSUE TITLE
`OSAVersion` missing units field

### ISSUE THREAD

**Issue by burnout87** [oda-hub/dispatcher-plugin-integral#61]
Related to [https://github.com/oda-hub/dispatcher-app/issues/250](https://github.com/oda-hub/dispatcher-app/issues/250)

Is it intended?

**Comment by burnout87** [comment]
Duplicated with #62

**Comment by volodymyrss** [comment]
> Related to [oda-hub/dispatcher-app#250](https://github.com/oda-hub/dispatcher-app/issues/250)
> 
> Is it intended?

yes

**Comment by volodymyrss** [comment]
> Duplicated with #62

I got confused, by bad. Indeed this is a duplicate. I thought we just have two issues not 3.
