### ISSUE TITLE
test fails in some cases?

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-plugin-integral#84]
https://github.com/oda-hub/dispatcher-app/runs/4368086679?check_suite_focus=true

maybe something is not set

**Comment by burnout87** [comment]
I think we handled by fixing some test [https://github.com/oda-hub/dispatcher-plugin-integral/pull/83](https://github.com/oda-hub/dispatcher-plugin-integral/pull/83)
