### ISSUE TITLE
Insert warning if in JEM-X light curve a user asks for <0.1s time bins

### ISSUE THREAD

**Issue by ferrigno** [oda-hub/dispatcher-plugin-integral#86]
j_ima_iros minimum time bin is 0.1 s with default to 4 s
the same is reflected in jemx_science_analysis

I have made a request from the API with 0.02 s bin job_id: 2bbfe99e
and one from the web interface with 0.02 s time bin  job_id: e2c6aace

They both returned a light curve with 4 s time bin. 

It is a good safety feature, but one should warn the user that the query parameters have been adapted to reflect limits.

[I do not know if this is even possible in automatic fashion, but we discussed something on weird inputs for ISGRI energy range]

**Comment by volodymyrss** [comment]
this is done, presumably.
