### ISSUE TITLE
few extra keywords needed in lightcurves

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-plugin-integral#9]
HEASOFT lcurve needs specific keywords in the lightcurve output. dispatcher plugin should set them. 

see there:

https://gitlab.astro.unige.ch/oda/api-clients/oda_api_wrapper/-/blob/master/oda_integral_wrapper/wrapper.py#L780
(lc is the object returned by oda_api)

and let's make a test for it!

**Comment by burnout87** [comment]
I might need some context.

- What is HEASOFT?
- Which specific keywords are to be set in the lightcurve output?

**Comment by volodymyrss** [comment]
good question! May not be worth going into this at this time. Either we discuss in voice tomorrow, or I do this - it's easy, and you focus on some other less domain-specific things.

**Comment by burnout87** [comment]
> good question! May not be worth going into this at this time. Either we discuss in voice tomorrow, or I do this - it's easy, and you focus on some other less domain-specific things.

If there is time, we can discuss it, and tomorrow is fine for me. Otherwise, as you said I will focus on something more specific to the core of the dispatcher, and then I will look it once done

**Comment by volodymyrss** [comment]
ok.

**Comment by burnout87** [comment]
In the end we never talked about this issue. Is it still important for the release?

**Comment by volodymyrss** [comment]
Maybe its addressed with #6 ? Since @ferrigno  mentioned it is ok now. Else I do not know.
I do not think it is urgent in any case.

**Comment by ferrigno** [comment]
It looks OK to me
